<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <li><a href="index.php" class="artliendex">Accueil</a></li>
        <li><a href="planning.php" class="artliendex">Planning</a></li>
        <?php if(!isset($_SESSION["login"])): ?>
        <li><a href="inscription.php" class="artliendex">Inscription</a></li>
        <li><a href="connexion.php" class="artliendex">Connexion</a></li>
        <?php else: ?>
        <li><a href="reservation-form.php" class="artliendex">Réservation</a></li>
        <li><a href="profil.php" class="artliendex">Profil</a></li>
        <li><a href="index.php?destroy=die" class="artliendex" id="artlienindexdc">Déconnexion (<?php echo $_SESSION["login"] ?>)</a></li>
        <?php endif; ?>
    </header>
    <div id="forFlex">
